### ISSUE TITLE
buy Runtime.pas

### ISSUE THREAD

**Issue by ghost** [ying32/DDNRuntime-examples#1]
where can I get the file "DDN.Runtime.pas", where do I buy it?

**Comment by KngStr** [comment]
Thanks for asking. This is current price.
My PayPay / AliPay account: kngstr@qq.com

Personal License
  Single Developer
  Unlimited location
  1 year upgrade
  Tool(dll to pas)
  Dcus: $499

Company License
  Up to 10 Developers
  Unlimited location
  1 year upgrade
  Tool(dll to pas)
  Dcus: $1999

Personal License Sale
  2-4 30% discount
  5-9 35% discount
  10+ 40% discount

**Comment by marcelomelofreitas** [comment]
You have sent $499.00 USD to kngstr@qq.com
We will let you know kngstr@qq.com that you have made the submission.

Tell us how the transaction went

**Comment by marcelomelofreitas** [comment]
send in your email from marcelo@se7esistemas.com.br

**Comment by KngStr** [comment]
Thanks. I got it.
The license file was sent to your email.
