### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by ghost** [ying32/DDNRuntime-examples#2]
run winforms example and click 2x in button and close form after
![memory leak](https://user-images.githubusercontent.com/7517306/127307890-2faf831e-8d63-47de-9be7-720b93e4c6cf.png)

**Comment by KngStr** [comment]
OK. ying32 is checking this problem.

**Comment by KngStr** [comment]
@marcelomelofreitas  
This error was fixed. Please pull the example

**Comment by ghost** [comment]
Now the memory leak comes out on the console since it is now a console application

![memory leak in console](https://user-images.githubusercontent.com/7517306/127321036-bc0c2a9f-5757-4838-9849-9608fb0f4e24.png)

**Comment by KngStr** [comment]
We will further look into the details of this problem and will keep you updated on the status of correction. We apologize for your inconvenience.

**Comment by KngStr** [comment]
@marcelomelofreitas   
New fix was uploaded. Please have a try.

PS: The new dcus are in trial folder.
