### ISSUE TITLE
WPF

### ISSUE THREAD

**Issue by ghost** [ying32/DDNRuntime-examples#3]
is this correct to generate the files for me to be able to use WPF?

{
   "OutputDir":".\\pt-BR",
   "Lang": "pt-BR",
   "CommonNamespace":"System.Windows",
   "MsLib": true,
   "CommonDepth": 0,
   "CommonTypes":[
     "System.ComponentModel.TypeConverter.StandardValuesCollection"
   ],
   "Assemblys":[
     "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\PresentationFramework.dll",
	 "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\WindowsBase.dll",
	 "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\PresentationCore.dll",
	 "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\System.Xaml.dll",
	 "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\UIAutomationTypes.dll",
	 "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\System.Windows.Input.Manipulations.dll"
   ]
}

**Comment by KngStr** [comment]
Yes. Do you get some problem?

**Comment by KngStr** [comment]
Sorry. Because this is json, you should encode some charaters.    
`\` should be `\\`

So your config file should be 
```
{
    "OutputDir": ".\\pt-BR",
    "Lang": "pt-BR",
    "CommonNamespace": "System.Windows",
    "MsLib": true,
    "CommonDepth": 0,
    "CommonTypes": [
        "System.ComponentModel.TypeConverter.StandardValuesCollection"
    ],
    "Assemblys": [
        "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\PresentationFramework.dll",
        "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\WindowsBase.dll",
        "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\PresentationCore.dll",
        "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\System.Xaml.dll",
        "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\UIAutomationTypes.dll",
        "C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework\\.NETFramework\\v4.0\\System.Windows.Input.Manipulations.dll"
    ]
}
```

**Comment by ghost** [comment]
Could you please make a WPF example that works?

**Comment by KngStr** [comment]
OK.

**Comment by KngStr** [comment]
@marcelomelofreitas 
Sorry. The current version is not compitable with WPF.
We are working on it.
We apologize for your inconvenience.

**Comment by ghost** [comment]
I managed to make it work here partially 

I sent it in your email

**Comment by KngStr** [comment]
Thanks. I got it. It do work.
The problem is gencode tool can not deal with a lot of common units.
We are working on improving gencode tool.

**Comment by KngStr** [comment]
@marcelomelofreitas 
WPF example is online. 
You can checkout or visit at https://github.com/ying32/DDNRuntime-examples/tree/main/examples/WinWPF
The new gencode tool, I will send it to your email.

PS: WPF config file example is here, https://github.com/ying32/DDNRuntime-examples/blob/main/Gencode-config-files/wpf.json

**Comment by ghost** [comment]
Fantastic, everything works, thank you very much
