### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by ghost** [ying32/DDNRuntime-examples#4]
Are there any plans for .net core 5 support?

**Comment by ying32** [comment]
Sorry, there are no plans at the moment.

**Comment by KngStr** [comment]
Do you want to use .net core 5 for windows or cross platform?

**Comment by ghost** [comment]
windows only

**Comment by KngStr** [comment]
OK. We will look into it.

**Comment by KngStr** [comment]
@marcelomelofreitas 
.net core is now supported. You can download it now.
