### ISSUE TITLE
Would it be possible to change the prefix of the names of classes, interfaces and units?

### ISSUE THREAD

**Issue by ghost** [ying32/DDNRuntime-examples#5]
Would it be possible for the generated classes and interfaces to have a different prefix? example...

DNDataTable -> IClrDataTable
TDNDateTime -> TClrDateTime
ToDNObjects -> ToClrObjects
DNObject -> IClrObject
TDNType -> TClrType
DNDateTime -> IClrDateTime

would it be possible to do this somehow to be configured in "Gencode" as a preferable prefix for the generated files and for the generated classes and interfaces?

**Comment by KngStr** [comment]
Sorry.
It's not necessary.
There is no plan for this.
